"""Build the daily VRP series from the RV panel and the EVZ history.

Rebuilds the RV panel first (cheap, extends with the tick backfill), then
assembles both VRP definitions and writes:
  - data/processed/vrp_daily.parquet
  - docs/reports/vrp_stylized_facts.md

The series is only as long as the ingested tick history; rerunning after the
backfill completes produces the full 2007-2025 sample with no code change.
"""

from __future__ import annotations

import polars as pl

from fxvrp.analysis.stylized_facts import facts_table
from fxvrp.analysis.vrp import build_vrp_series
from fxvrp.config import load_config
from fxvrp.log import get_logger
from fxvrp.realized.panel import build_panel

logger = get_logger("scripts.build_vrp")


def main() -> None:
    config = load_config()

    panel_result = build_panel(
        config.paths.raw_dir,
        config.dukascopy,
        config.realized,
        config.dukascopy.start_date,
        config.dukascopy.end_date,
    )
    panel_path = config.paths.processed_dir / "rv_daily.parquet"
    panel_path.parent.mkdir(parents=True, exist_ok=True)
    panel_result.frame.write_parquet(panel_path)

    evz = pl.read_parquet(config.paths.raw_dir / "fred" / "EVZCLS.parquet")
    series = build_vrp_series(panel_result.frame, evz, config.vrp)
    out_path = config.paths.processed_dir / "vrp_daily.parquet"
    series.write_parquet(out_path)
    logger.info("wrote %s (%d rows)", out_path, series.height)

    table = facts_table(
        series,
        ["iv_sq", "rv_fwd_ann", "vrp_ex_post", "vrp_ex_ante"],
        config.vrp.hac_maxlags,
    )
    report_dir = config.paths.reports_dir
    report_dir.mkdir(parents=True, exist_ok=True)
    lines = [
        "# VRP stylized facts\n",
        "Generated by `scripts/build_vrp.py`; extends as the tick backfill completes.\n",
        f"\nSeries rows: {series.height}; ex-post observations: "
        f"{series.drop_nulls('vrp_ex_post').height}; ex-ante observations: "
        f"{series.drop_nulls('vrp_ex_ante').height}.\n",
        "\nAll quantities are annualised 30-calendar-day variances; the mean's",
        " t-statistic uses Newey-West standard errors "
        f"(bandwidth {config.vrp.hac_maxlags} days) because the forward window overlaps.\n",
        "\n| series | n | mean | HAC t | std | skew | ex.kurt | frac>0 | AC(1) | AC(22) |\n",
        "|---|---|---|---|---|---|---|---|---|---|\n",
    ]
    for row in table.iter_rows(named=True):
        lines.append(
            f"| {row['series']} | {row['n']} | {row['mean']:.6f} | {row['hac_t']:.2f} "
            f"| {row['std']:.6f} | {row['skew']:.2f} | {row['ex_kurt']:.2f} "
            f"| {row['frac_pos']:.2f} | {row['ac_1d']:.2f} | {row['ac_22d']:.2f} |\n"
        )
    (report_dir / "vrp_stylized_facts.md").write_text("".join(lines), encoding="utf-8")
    logger.info("wrote %s", report_dir / "vrp_stylized_facts.md")


if __name__ == "__main__":
    main()
