"""Generate the data-quality report from everything currently in data/raw/.

Writes docs/reports/data_quality.md: per-day tick metrics (spreads, gaps, stale
runs, crossed quotes), flagged days, and chain snapshot coverage. The paper's
appendix shows this report rather than asserting the data is clean.
"""

from __future__ import annotations

from datetime import date
from pathlib import Path

import polars as pl

from fxvrp.config import load_config
from fxvrp.data.quality import DayQuality, day_quality, quality_table
from fxvrp.log import get_logger

logger = get_logger("scripts.data_quality_report")


def tick_quality(raw_dir: Path, instrument: str) -> pl.DataFrame:
    config = load_config()
    tick_dir = raw_dir / "ticks" / instrument.lower()
    results: list[DayQuality] = []
    for path in sorted(tick_dir.glob("*.parquet")):
        day = date.fromisoformat(path.stem)
        frame = pl.read_parquet(path)
        results.append(day_quality(frame, day, config.quality, config.dukascopy.pip))
    return quality_table(results) if results else pl.DataFrame()


def chain_coverage(raw_dir: Path) -> pl.DataFrame:
    rows = []
    chains_dir = raw_dir / "chains"
    if chains_dir.exists():
        for symbol_dir in sorted(chains_dir.iterdir()):
            for path in sorted(symbol_dir.glob("*.parquet")):
                frame = pl.read_parquet(path)
                two_sided = frame.filter(
                    (pl.col("bid") > 0) & (pl.col("ask") > pl.col("bid"))
                ).height
                rows.append(
                    {
                        "symbol": symbol_dir.name,
                        "date": path.stem,
                        "contracts": frame.height,
                        "expiries": frame["expiry"].n_unique(),
                        "two_sided_frac": two_sided / frame.height if frame.height else 0.0,
                    }
                )
    return pl.DataFrame(rows)


def _to_markdown(frame: pl.DataFrame) -> str:
    if frame.height == 0:
        return "_no data ingested yet_\n"
    header = "| " + " | ".join(frame.columns) + " |"
    rule = "|" + "|".join(["---"] * len(frame.columns)) + "|"
    body = ["| " + " | ".join(_fmt(v) for v in row) + " |" for row in frame.iter_rows()]
    return "\n".join([header, rule, *body]) + "\n"


def _fmt(value: object) -> str:
    if isinstance(value, float):
        return f"{value:.3f}"
    return str(value)


def main() -> None:
    config = load_config()
    ticks = tick_quality(config.paths.raw_dir, config.dukascopy.instrument)
    chains = chain_coverage(config.paths.raw_dir)

    out_dir = config.paths.reports_dir
    out_dir.mkdir(parents=True, exist_ok=True)
    out_path = out_dir / "data_quality.md"

    sections = ["# Data-quality report\n", "Generated by `scripts/data_quality_report.py`.\n"]
    sections.append("\n## EURUSD ticks, per day\n\n")
    sections.append(_to_markdown(ticks))
    if ticks.height:
        flagged = ticks.filter(pl.col("flag_low_ticks"))
        sections.append(f"\nDays flagged for low tick count: **{flagged.height}**\n")
    sections.append("\n## Chain snapshots\n\n")
    sections.append(_to_markdown(chains))

    out_path.write_text("".join(sections), encoding="utf-8")
    logger.info(
        "wrote %s (%d tick days, %d chain snapshots)", out_path, ticks.height, chains.height
    )


if __name__ == "__main__":
    main()
